apiVersion: v1
kind: Service
metadata:
  name: {{ template "mdb.servicename" . }}
  labels:
    app: {{ template "mdb.name" . }}
    chart: {{ template "mdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalIPs }} 
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 2 }}
  {{- end}}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
      targetPort: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    app: {{ template "mdb.name" . }}
    release: {{ .Release.Name }}
