chart-dirs:
  - ops-charts
chart-repos:
  - ops-charts=https://jsoyee.github.io/charts
check-version-increment: true
debug: true
remote: origin
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
