{{- if .Values.statefulset.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apollo.fullname" . }}-headless
  labels:
    app: {{ template "apollo.name" . }}
    chart: {{ template "apollo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
      targetPort: {{ $key }}
{{ toYaml $value | indent 6 }}
    {{- end }}
  selector:
    app: {{ template "apollo.name" . }}
    release: {{ .Release.Name }}
{{- end -}}
