{{- if .Values.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ template "mdb.fullname" . }}
  labels:
    app: {{ template "mdb.name" . }}
    chart: {{ template "mdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ template "mdb.version" . }}
    canary: "false"
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.statefulset.enabled }}
  serviceName: {{ template "mdb.servicename" . }}-headless
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy:
{{ toYaml .Values.deploymentStrategy | indent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "mdb.name" . }}
      release: {{ .Release.Name }}
      canary: "false"
  template:
    metadata:
    {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8}}
    {{- end }}
      labels:
        app: {{ template "mdb.name" . }}
        release: {{ .Release.Name }}
        version: {{ template "mdb.version" . }}
        canary: "false"
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
{{- include "mdb.imagePullSecrets" . | indent 6 }}
      {{- if .Values.initContainers }}
      initContainers:
{{ toYaml .Values.initContainers | indent 8 }}
      {{- end }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      hostAliases:
{{ toYaml .Values.hostAliases | indent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "mdb.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.securityContext }}                                                
          securityContext:                                                                 
{{ toYaml .Values.securityContext | indent 12 }}                                           
          {{- end }} 
          {{- if .Values.lifecycle }}
          lifecycle:
{{ toYaml .Values.lifecycle | indent 12 }}
          {{- end }}
          {{- if .Values.startCommand }}
          command:
{{ toYaml .Values.startCommand |indent 12 }}
          {{- end }}
          env:
          {{- if .Values.javaOpts }}
            - name: JAVA_TOOL_OPTIONS      
              value: {{ .Values.javaOpts }}
          {{- end }}
{{ toYaml .Values.env | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            {{- range $key, $value := .Values.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
              protocol: {{ $value.protocol }}
            {{- end }}
          {{- if .Values.healthCheck.livenessProbe.enabled }}
          livenessProbe:
            {{- if eq .Values.healthCheck.type "http" }}
            httpGet:
              path: {{ .Values.healthCheck.httpPath }}
              port: {{ .Values.healthCheck.port }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.healthCheck.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.healthCheck.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.healthCheck.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.healthCheck.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.healthCheck.readinessProbe.enabled }}
          readinessProbe:
            {{- if eq .Values.healthCheck.type "http" }}
            httpGet:
              path: {{ .Values.healthCheck.httpPath }}
              port: {{ .Values.healthCheck.port }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.healthCheck.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.healthCheck.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.healthCheck.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.healthCheck.readinessProbe.failureThreshold }}
          {{- end }}
          volumeMounts:
            {{- if .Values.config.enabled }}
            - name: {{ template "mdb.name" . }}-conf
              mountPath: {{ .Values.config.mountPath }}
              subPath: {{ .Values.config.subPath }}
              readOnly: {{ .Values.config.readOnly }}
            {{- end }}
            {{- if .Values.existConfig.enabled }}
            - name: {{ template "mdb.name" . }}-exist-conf
              mountPath: {{ .Values.existConfig.mountPath }}
              subPath: {{ .Values.existConfig.subPath }}
              readOnly: {{ .Values.existConfig.readOnly }}
            {{- end }}
            {{- if .Values.secret.enabled }}
            - name: {{ template "mdb.name" . }}-secret
              mountPath: {{ .Values.secret.mountPath }}
              subPath: {{ .Values.secret.subPath }}
              readOnly: {{ .Values.secret.readOnly }}
            {{- end }}
            {{- if .Values.existSecret.enabled }}
            - name: {{ template "mdb.name" . }}-exist-secret
              mountPath: {{ .Values.existSecret.mountPath }}
              subPath: {{ .Values.existSecret.subPath }}
              readOnly: {{ .Values.existSecret.readOnly }}
            {{- end }}
{{- if .Values.persistentVolume.mountPaths }} 
{{ toYaml .Values.persistentVolume.mountPaths | indent 12 }}
{{- end }}
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
{{- end }}
        {{- if .Values.additionalContainers }}
{{ toYaml .Values.additionalContainers | indent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.config.enabled }}
        - name: {{ template "mdb.name" . }}-conf
          configMap:
            name: {{ template "mdb.fullname" . }}
        {{- end }}
        {{- if .Values.existConfig.enabled }}
        - name: {{ template "mdb.name" . }}-exist-conf
          configMap:
            name: {{ .Values.existConfig.name }}
        {{- end }}
        {{- if .Values.secret.enabled }}
        - name: {{ template "mdb.name" . }}-secret
          secret:
            secretName: {{ template "mdb.fullname" . }}
        {{- end }}
        {{- if .Values.existSecret.enabled }}
        - name: {{ template "mdb.name" . }}-exist-secret
          secret:
            secretName: {{ .Values.existSecret.name }}
        {{- end }}
        {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
        {{- end }}
{{- if not .Values.statefulset.enabled }}
          {{- if .Values.persistentVolume.enabled }}
        - name: data-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolume.existingClaim | default (include "mdb.fullname" .) }}
          {{- else }}
        - name: data-storage
          emptyDir: {}
          {{- end }}
{{- else }}
  {{- if .Values.persistentVolume.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data-storage
      labels:
        app: {{ template "mdb.name" . }}
        chart: {{ template "mdb.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      accessModes:
        - {{ .Values.persistentVolume.accessMode | quote }}
      annotations:
      {{- range $key, $value := $.Values.persistentVolume.annotations }}
        {{ $key }}: {{ $value }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistentVolume.size }}
          {{- if .Values.persistentVolume.storageClass }}
            {{- if (eq "-" .Values.persistentVolume.storageClass) }}
      storageClassName: ""
            {{- else }}
      storageClassName: "{{ .Values.persistentVolume.storageClass }}"
            {{- end }}
          {{- end }}
  {{- else }}
        - name: data-storage
          emptyDir: {}
  {{- end }}
{{- end -}}
